;; -*- mode: eask; lexical-binding: t -*-

(defvar version "0.1.0")

(package "{{cookiecutter.proj_name}}-rs-el"
         version
         "")

(website-url "")
(keywords )

(package-file "{{cookiecutter.proj_name}}.el")
(files "src/el_{{cookiecutter.proj_name}}/*.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")

(depends-on "emacs" "30.2")
