#!/usr/bin/env python3
"""
Generalized script to build all docs.
Covers:

- Sphinx
- mdbook
- rustdoc

TODO: prolog, dotnet, elixir, kotlin, prolog, rocq

"""
# ruff.ignore.in.file
from __future__ import annotations

# Imports:
# ##-- stdlib imports
import datetime
import enum
import functools as ftz
import itertools as itz
import logging as logmod
import pathlib as pl
import re
import time
import collections
import contextlib
import hashlib
from copy import deepcopy
from uuid import UUID, uuid1
from weakref import ref
import atexit # for @atexit.register
import faulthandler
# ##-- end stdlib imports

import sys
import sh

# ##-- types
# isort: off
# General
import abc
import collections.abc
import typing
import types
from typing import cast, assert_type, assert_never
from typing import Generic, NewType, Never
from typing import no_type_check, final, override, overload
# Protocols and Interfaces:
from typing import Protocol, runtime_checkable
# isort: on
# ##-- end types

# ##-- type checking
# isort: off
if typing.TYPE_CHECKING:
    from typing import Final, ClassVar, Any, Self
    from typing import Literal, LiteralString
    from typing import TypeGuard
    from collections.abc import Iterable, Iterator, Callable, Generator
    from collections.abc import Sequence, Mapping, MutableMapping, Hashable

    from jgdv import Maybe
## isort: on
# ##-- end type checking

##-- logging
logging = logmod.getLogger(__name__)
##-- end logging

# Core Vars:
cargo_file      : Final[pl.Path]  = pl.Path("Cargo.toml")
book_file       : Final[pl.Path]  = pl.Path("book.toml")
docs_out        : Final[pl.Path]  = pl.Path(".temp/docs")
sphinx_out      : Final[pl.Path]  = docs_out / "sphinx"
mdbook_out      : Final[pl.Path]  = docs_out / "mdbook"
rustdoc_out     : Final[pl.Path]  = docs_out / "rustdoc"

source_dir      : Final[pl.Path]  = pl.Path("src")
conf_dir        : Final[pl.Path]  = pl.Path("src/_docs")

# Secondary
doctree_dir     : Final[pl.Path]  = sphinx_out / ".doctrees"
log_file        : Final[pl.Path]  = pl.Path(".temp/logs/sphinx.log")
sphinx_builder  : Final[str]      = "bibhtml"
# Body:

def run_sphinx():
    if not (conf_dir / "conf.py").exists():
        print("Skipping Sphinx")
        return
    try:
        sphinx     = sh.sphinx_build
    except sh.CommandNotFound as err:
        print("Sphinx not found")
        return

    print("Running Sphinx")
    sphinx(
        # "--fresh-env",
        "--conf-dir", conf_dir,
        "--doctree-dir", doctree_dir,
        "--warning-file", log_file,
        "--builder", sphinx_builder,
        source_dir,
        sphinx_out,
        )

def run_mdbook():
    if not book_file.exists():
        print("Skipping Mdbook")
        return
    try:
        mdbook     = sh.mdbook
    except sh.CommandNotFound as err:
        print("MdBook not found")
        return

    print("Running MdBook")
    mdbook("build", dest_dir=str(mdbook_out))

def run_rustdoc():
    if not cargo_file.exists():
        print("Skipping Rustdoc")
        return
    try:
        cargo_doc  = sh.cargo.doc
    except sh.CommandNotFound as err:
        print("Cargo doc not found")
        return

    print("Running Rustdoc")
    cargo_doc("--workspace", target_dir=str(rustdoc_out))

def main():
    print("Building Documentation")
    # TODO add switches to control each
    run_rustdoc()
    run_mdbook()
    run_sphinx()
    # TODO fixup: create a master index.html, link to each sub doc.

    sys.exit(0)

##-- ifmain
if __name__ == "__main__":
    main()
##-- end ifmain
