#!/usr/bin/env bash
#  install-asdf-plugins -*- mode: sh -*-

# shellcheck disable=SC1091
source "$POLY_SRC/lib/lib-util.bash"
if [[ -e "$POLYGLOT_ROOT/.tasks/task-util.bash" ]]; then
   # shellcheck disable=SC1091
    source "$POLYGLOT_ROOT/.tasks/task-util.bash"
fi

tdot "[asdf]" "Installing Plugins..."
# This allows you to just install direnv, then direnv allow,
# to install the other plugins
if [[ -e ".asdf.plugins" ]]; then
    while read -r pname url; do
        if [[ -n "$pname" ]]; then
            tdot "[asdf]" "Adding $pname..."
            asdf plugin add "$pname" "${url:-}"
        fi
    done < ".asdf.plugins"
fi
